import { useMemo, useState } from "react";
import JSZip from "jszip";
import QRCode from "qrcode";
import { ArrowLeft, CheckCircle2, Download, ExternalLink, Eye, FileArchive, History, QrCode, RefreshCw, Search, Square, UserMinus, UserPlus, Users, X } from "lucide-react";
import { Link, Navigate } from "react-router";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/hooks/useAuth";
import { trpc } from "@/providers/trpc";
import { programmeDays } from "./FinalCandidateProgramme";

type QrPreview = { sessionId: number; title: string; url: string; image: string };
type CandidateRow = { id: number; firstName: string; lastName: string; email: string; phoneNumber: string; checkedInAt: unknown };

function stableScheduleKey(dayNumber: number, time: string) { return `edition18-day-${dayNumber}-slot-${time.slice(0, 5).replace(":", "")}`; }
function downloadBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
function csvCell(value: unknown) { return `"${String(value ?? "").replaceAll('"', '""')}"`; }

export default function AdminAttendancePage() {
  const { user, isLoading } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/admin/login" });
  const isSuperAdmin = user?.role === "admin" && user.adminRole === "super_admin";
  const utils = trpc.useUtils();
  const sessions = trpc.attendance.listSessions.useQuery(undefined, { enabled: isSuperAdmin, retry: false, refetchInterval: 10000 });
  const [qr, setQr] = useState<QrPreview | null>(null);
  const [attendanceSession, setAttendanceSession] = useState<{ id: number; title: string } | null>(null);
  const [search, setSearch] = useState("");
  const attendance = trpc.attendance.sessionAttendance.useQuery({ sessionId: attendanceSession?.id ?? 0 }, { enabled: Boolean(attendanceSession), retry: false, refetchInterval: attendanceSession ? 10000 : false });
  const sessionByKey = useMemo(() => new Map((sessions.data ?? []).map((item) => [item.scheduleKey, item])), [sessions.data]);
  const openSessions = useMemo(() => (sessions.data ?? []).filter((session) => Boolean(session.isOpen)), [sessions.data]);
  const programmeSessions = useMemo(() => programmeDays.flatMap((day, dayIndex) => day.events.map((event, eventIndex) => {
    const stableKey = stableScheduleKey(dayIndex + 1, event.time); const legacyKey = `d${dayIndex + 1}-e${eventIndex + 1}`; const saved = sessionByKey.get(stableKey) ?? sessionByKey.get(legacyKey);
    return { scheduleKey: saved?.scheduleKey ?? stableKey, title: event.title, dayNumber: dayIndex + 1, timeLabel: event.time };
  })), [sessionByKey]);

  async function showQr(sessionId: number, title: string, token: string) { const url = `${window.location.origin}/presence/session/${token}`; const image = await QRCode.toDataURL(url, { width: 900, margin: 3, errorCorrectionLevel: "H", color: { dark: "#173f39", light: "#ffffff" } }); setQr({ sessionId, title, url, image }); }
  const open = trpc.attendance.openSession.useMutation({ onSuccess: async (data, input) => { await showQr(data.id, input.title, data.token); await utils.attendance.listSessions.invalidate(); toast.success("تم فتح تسجيل الحضور"); }, onError: (error) => toast.error(error.message) });
  const close = trpc.attendance.closeSession.useMutation({ onSuccess: async (_, input) => { if (qr?.sessionId === input.id) setQr(null); toast.success("تم إغلاق تسجيل الحضور"); await Promise.all([utils.attendance.listSessions.invalidate(), utils.attendance.sessionAttendance.invalidate()]); }, onError: (error) => toast.error(error.message) });
  const prepare = trpc.attendance.prepareSessions.useMutation({ onError: (error) => toast.error(error.message) });
  const manual = trpc.attendance.setManualAttendance.useMutation({ onSuccess: async () => { toast.success("تم تصحيح الحضور وتسجيل العملية"); await Promise.all([attendance.refetch(), utils.attendance.listSessions.invalidate()]); }, onError: (error) => toast.error(error.message) });

  async function downloadAllQr() {
    const prepared = await prepare.mutateAsync({ sessions: programmeSessions }); const zip = new JSZip();
    await Promise.all(prepared.map(async (session) => { const url = `${window.location.origin}/presence/session/${session.token}`; const dataUrl = await QRCode.toDataURL(url, { width: 900, margin: 3, errorCorrectionLevel: "H" }); zip.file(`session-${session.id}-${session.scheduleKey}.png`, dataUrl.split(",")[1], { base64: true }); }));
    downloadBlob(await zip.generateAsync({ type: "blob" }), "qr-presence-edition-18.zip"); await sessions.refetch(); toast.success("تم تحميل جميع رموز QR");
  }
  function exportCsv() {
    if (!attendance.data || !attendanceSession) return; const rows = [...attendance.data.present.map((candidate) => ({ ...candidate, status: "Présent" })), ...attendance.data.absent.map((candidate) => ({ ...candidate, status: attendance.data.session?.isOpen ? "Non pointé" : "Absent" }))];
    const csv = ["Nom,Prénom,Email,Téléphone,Statut,Heure de pointage", ...rows.map((row) => [row.lastName, row.firstName, row.email, row.phoneNumber, row.status, row.checkedInAt ? new Date(row.checkedInAt as string).toLocaleString("fr-MA") : ""].map(csvCell).join(","))].join("\r\n");
    downloadBlob(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" }), `presence-session-${attendanceSession.id}.csv`);
  }
  const normalizedSearch = search.trim().toLowerCase(); const filterCandidates = (items: CandidateRow[]) => !normalizedSearch ? items : items.filter((candidate) => `${candidate.firstName} ${candidate.lastName} ${candidate.email}`.toLowerCase().includes(normalizedSearch));
  const actionLabels: Record<string, string> = { open: "فتح الحضور", close: "إغلاق الحضور", manual_add: "إضافة حضور يدوياً", manual_remove: "إلغاء حضور يدوياً" };

  if (isLoading) return <div className="p-20 text-center">Chargement…</div>;
  if (!isSuperAdmin) return <Navigate to="/admin" replace />;
  return <div className="min-h-screen bg-slate-50 p-4 md:p-8" lang="ar" dir="rtl"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-3xl bg-[linear-gradient(125deg,#102f2b,#4A9B8E)] p-7 text-white"><div className="flex flex-wrap gap-2"><Link to="/admin/final-candidates"><Button className="bg-white text-[#173f39] hover:bg-white/90"><ArrowLeft className="ml-2 h-4 w-4" />المرشحون النهائيون</Button></Link><Button variant="outline" className="border-white/30 bg-white/10 text-white hover:bg-white/20 hover:text-white" disabled={prepare.isPending} onClick={downloadAllQr}><FileArchive className="ml-2 h-4 w-4" />{prepare.isPending ? "جارٍ التحضير…" : "تحميل جميع رموز QR"}</Button><Button variant="outline" className="border-white/30 bg-white/10 text-white hover:bg-white/20 hover:text-white" onClick={() => sessions.refetch()}><RefreshCw className="ml-2 h-4 w-4" />تحديث</Button></div><h1 className="mt-6 text-3xl font-black">إدارة الحضور عبر QR Code</h1><p className="mt-2 text-white/75">لكل حصة رمز واحد وثابت، صالح لجميع المشاركين المؤكدين أثناء فتح الحضور.</p></header>
    <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center gap-3"><span className="font-black text-slate-700">الحصص المفتوحة الآن:</span>{openSessions.length ? openSessions.map((session) => <Button key={session.id} size="sm" variant={qr?.sessionId === session.id ? "default" : "outline"} className={qr?.sessionId === session.id ? "bg-[#4A9B8E] hover:bg-[#3D7A6F]" : ""} onClick={() => showQr(session.id, session.title, session.token)}><QrCode className="ml-1 h-4 w-4" />{session.title}</Button>) : <span className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-500">لا توجد حصة مفتوحة</span>}</div></section>
    {qr ? <section className="grid gap-6 rounded-3xl border border-emerald-200 bg-white p-6 shadow-xl lg:grid-cols-[360px_1fr] lg:items-center"><img src={qr.image} alt={`QR Code ${qr.title}`} className="mx-auto w-full max-w-[340px]"/><div><span className="rounded-full bg-emerald-100 px-3 py-1 text-sm font-bold text-emerald-800">رمز الحصة</span><h2 className="mt-4 text-3xl font-black">{qr.title}</h2><p className="mt-3 break-all text-sm text-slate-500" dir="ltr">{qr.url}</p><div className="mt-5 flex flex-wrap gap-2"><a href={qr.image} download={`qr-presence-session-${qr.sessionId}.png`}><Button><Download className="ml-2 h-4 w-4"/>تحميل QR</Button></a><a href={qr.url} target="_blank" rel="noreferrer"><Button variant="outline"><ExternalLink className="ml-2 h-4 w-4"/>فتح الرابط</Button></a><Button variant="ghost" onClick={() => setQr(null)}><X className="ml-2 h-4 w-4"/>إخفاء</Button></div></div></section> : null}
    {attendanceSession && attendance.data ? <section className="rounded-3xl border bg-white p-6 shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-black">متابعة الحضور والغياب</h2><p className="mt-1 text-slate-500">{attendanceSession.title}</p><div className="mt-3 flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-emerald-100 px-3 py-1 font-black text-emerald-800">{attendance.data.present.length} حاضر / {attendance.data.total} مشارك</span><span className="rounded-full bg-slate-100 px-3 py-1">الفتح: {attendance.data.session?.openedAt ? new Date(attendance.data.session.openedAt).toLocaleString("fr-MA") : "—"}</span><span className="rounded-full bg-slate-100 px-3 py-1">الإغلاق: {attendance.data.session?.closedAt ? new Date(attendance.data.session.closedAt).toLocaleString("fr-MA") : "—"}</span></div></div><div className="flex gap-2"><Button variant="outline" onClick={exportCsv}><Download className="ml-2 h-4 w-4"/>CSV</Button><Button variant="outline" onClick={() => attendance.refetch()}><RefreshCw className="ml-2 h-4 w-4"/>تحديث</Button><Button variant="ghost" onClick={() => setAttendanceSession(null)}><X className="h-5 w-5"/></Button></div></div><div className="relative mt-5"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400"/><Input className="pr-10" placeholder="البحث بالاسم أو البريد الإلكتروني…" value={search} onChange={(event) => setSearch(event.target.value)}/></div><div className="mt-5 grid gap-6 xl:grid-cols-2"><CandidateAttendanceList title={`الحاضرون (${filterCandidates(attendance.data.present).length})`} candidates={filterCandidates(attendance.data.present)} present busy={manual.isPending} onToggle={(id) => manual.mutate({ sessionId: attendanceSession.id, finalCandidateId: id, present: false })}/><CandidateAttendanceList title={`${attendance.data.session?.isOpen ? "غير المسجلين بعد" : "الغائبون"} (${filterCandidates(attendance.data.absent).length})`} candidates={filterCandidates(attendance.data.absent)} busy={manual.isPending} onToggle={(id) => manual.mutate({ sessionId: attendanceSession.id, finalCandidateId: id, present: true })}/></div><div className="mt-6 rounded-2xl border"><h3 className="flex items-center gap-2 bg-slate-50 px-4 py-3 font-black"><History className="h-4 w-4"/>سجل العمليات</h3><div className="max-h-56 divide-y overflow-auto">{attendance.data.logs.length ? attendance.data.logs.map((log) => <div key={log.id} className="flex flex-wrap justify-between gap-2 p-3 text-sm"><span><b>{log.adminName}</b> — {actionLabels[log.action] ?? log.action}{log.firstName ? `: ${log.firstName} ${log.lastName}` : ""}</span><span dir="ltr" className="text-slate-500">{new Date(log.createdAt).toLocaleString("fr-MA")}</span></div>) : <p className="p-4 text-center text-slate-500">لا توجد عمليات مسجلة.</p>}</div></div></section> : attendanceSession ? <section className="rounded-3xl border bg-white p-10 text-center">جارٍ تحميل اللوائح…</section> : null}
    <div className="space-y-6">{programmeDays.map((day, dayIndex) => <section key={day.day} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between bg-slate-100 p-4"><h2 className="text-xl font-black">{day.day}</h2><span className="text-sm text-slate-500">{day.events.length} حصص</span></div><div className="divide-y">{day.events.map((event, eventIndex) => { const stableKey = stableScheduleKey(dayIndex + 1, event.time); const legacyKey = `d${dayIndex + 1}-e${eventIndex + 1}`; const saved = sessionByKey.get(stableKey) ?? sessionByKey.get(legacyKey); const busy = open.isPending || close.isPending; return <div key={stableKey} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className={`mt-1 h-3 w-3 shrink-0 rounded-full ${saved?.isOpen ? "bg-emerald-500" : "bg-slate-300"}`}/><div><p className="font-black">{event.title}</p><p className="mt-1 text-sm text-slate-500" dir="ltr">{event.time}</p>{saved ? <p className="mt-1 text-xs text-slate-400">{saved.isOpen ? `مفتوحة منذ ${new Date(saved.openedAt).toLocaleTimeString("fr-MA")}` : saved.closedAt ? `أغلقت في ${new Date(saved.closedAt).toLocaleTimeString("fr-MA")}` : "لم تفتح بعد"}</p> : null}</div></div><div className="flex flex-wrap items-center gap-2">{saved ? <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700"><Users className="h-3.5 w-3.5"/>{saved.attendanceCount} حاضر</span> : null}{saved ? <Button size="sm" variant="outline" onClick={() => showQr(saved.id, event.title, saved.token)}><QrCode className="ml-1 h-4 w-4"/>QR</Button> : null}{saved ? <Button size="sm" variant="outline" onClick={() => { setAttendanceSession({ id: saved.id, title: event.title }); setSearch(""); }}><Eye className="ml-1 h-4 w-4"/>اللائحة</Button> : null}{saved?.isOpen ? <Button size="sm" variant="destructive" disabled={busy} onClick={() => window.confirm("هل أنتم متأكدون من إغلاق تسجيل الحضور لهذه الحصة؟") && close.mutate({ id: saved.id })}><Square className="ml-1 h-4 w-4"/>إغلاق</Button> : <Button size="sm" className="bg-emerald-700 hover:bg-emerald-800" disabled={busy} onClick={() => open.mutate({ scheduleKey: saved?.scheduleKey ?? stableKey, title: event.title, dayNumber: dayIndex + 1, timeLabel: event.time })}><CheckCircle2 className="ml-1 h-4 w-4"/>{open.isPending ? "جارٍ الفتح…" : "فتح"}</Button>}</div></div>; })}</div></section>)}</div>
  </div></div>;
}

function CandidateAttendanceList({ title, candidates, present = false, busy, onToggle }: { title: string; candidates: CandidateRow[]; present?: boolean; busy: boolean; onToggle: (id: number) => void }) {
  return <div className={`overflow-hidden rounded-2xl border ${present ? "border-emerald-200" : "border-amber-200"}`}><h3 className={`px-4 py-3 font-black ${present ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{title}</h3>{candidates.length ? <div className="max-h-[480px] overflow-auto"><table className="w-full text-right text-sm"><thead className="sticky top-0 bg-white"><tr className="border-b"><th className="p-3">الاسم الكامل</th><th className="p-3">البريد الإلكتروني</th><th className="p-3">الإجراء</th></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.id} className="border-b last:border-0"><td className="p-3 font-bold">{candidate.firstName} {candidate.lastName}</td><td className="p-3" dir="ltr">{candidate.email}</td><td className="p-3"><Button size="sm" variant={present ? "destructive" : "outline"} disabled={busy} onClick={() => (!present || window.confirm(`هل أنتم متأكدون من إلغاء حضور ${candidate.firstName} ${candidate.lastName}؟`)) && onToggle(candidate.id)}>{present ? <UserMinus className="ml-1 h-4 w-4"/> : <UserPlus className="ml-1 h-4 w-4"/>}{present ? "إلغاء" : "إضافة"}</Button></td></tr>)}</tbody></table></div> : <p className="p-6 text-center text-slate-500">لا يوجد أي اسم في هذه اللائحة.</p>}</div>;
}
