import { useMemo, useState } from "react";
import { ArrowRight, Award, Download, History, MinusCircle, PlusCircle, RefreshCw, Search, Trophy } from "lucide-react";
import { Link, Navigate } from "react-router";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/hooks/useAuth";
import { formatMoroccoDateTime } from "@/lib/morocco-time";
import { trpc } from "@/providers/trpc";

export default function AdminScoresPage(){
  const {user,isLoading}=useAuth({redirectOnUnauthenticated:true,redirectPath:"/admin/login"}); const allowed=user?.role==="admin"&&(user.adminRole!=="interview_admin"||user.adminPermissions?.includes("scores"));
  const dashboard=trpc.attendance.adminScoreDashboard.useQuery(undefined,{enabled:allowed,retry:false,refetchInterval:15000}); const [search,setSearch]=useState(""); const [action,setAction]=useState("all"); const [form,setForm]=useState({candidateId:"",points:"5",reason:""});
  const adjustment=trpc.attendance.addManualPoints.useMutation({onSuccess:async()=>{toast.success("تم تسجيل التصحيح مع اسم المسؤول والسبب");setForm({...form,points:"5",reason:""});await dashboard.refetch();},onError:(error)=>toast.error(error.message)});
  const filteredHistory=useMemo(()=>{const query=search.trim().toLowerCase();return (dashboard.data?.history??[]).filter((entry)=>(action==="all"||entry.actionType===action)&&(!query||`${entry.firstName} ${entry.lastName} ${entry.email} ${entry.title} ${entry.detail??""}`.toLowerCase().includes(query)));},[dashboard.data,search,action]);
  const exportRanking=()=>{if(!dashboard.data)return;const csv=["Rang,Nom,Prénom,Email,Points",...dashboard.data.ranking.map((candidate)=>[candidate.rank,candidate.lastName,candidate.firstName,candidate.email,candidate.totalPoints].map(csvCell).join(","))].join("\r\n");downloadCsv(csv,"classement-general-points.csv");};
  if(isLoading)return <div className="p-20 text-center">Chargement…</div>;if(!allowed)return <Navigate to={user?.adminRole==="interview_admin"?"/admin/profile":"/admin/login"} replace/>;
  return <div className="min-h-screen bg-slate-50 p-2 sm:p-4 md:p-8" lang="ar" dir="rtl"><main className="mx-auto max-w-7xl space-y-6"><header className="rounded-2xl bg-[linear-gradient(125deg,#102f2b,#4A9B8E)] p-4 text-white sm:rounded-3xl sm:p-7"><Link to={user?.adminRole === "interview_admin" && !user.adminPermissions?.includes("attendance") ? "/admin/profile" : "/admin/attendance"} className="inline-flex items-center gap-2 rounded-xl bg-white/15 px-4 py-2 font-bold"><ArrowRight className="h-4 w-4"/>{user?.adminRole === "interview_admin" && !user.adminPermissions?.includes("attendance") ? "العودة إلى الملف الشخصي" : "العودة إلى الحضور"}</Link><h1 className="mt-6 text-3xl font-black">إدارة نقاط المشاركين</h1><p className="mt-2 text-white/75">الترتيب، سجل النقاط والتصحيحات الإدارية المعللة.</p></header>
    <section className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><form className="rounded-3xl border bg-white p-6 shadow-sm" onSubmit={(event)=>{event.preventDefault();const points=Number(form.points);if(points<0&&!window.confirm("هذا التصحيح سيخصم نقاطاً من المشارك. هل تريدون المتابعة؟"))return;adjustment.mutate({finalCandidateId:Number(form.candidateId),points,reason:form.reason});}}><h2 className="flex items-center gap-2 text-xl font-black"><Award className="h-5 w-5 text-amber-600"/>تصحيح استثنائي</h2><p className="mt-2 text-sm leading-6 text-slate-500">استعملوا قيمة موجبة للإضافة أو سالبة للخصم. يبقى التصحيح محفوظاً في السجل ولا يمكن إخفاؤه.</p><div className="mt-5 space-y-4"><div><Label>المشارك</Label><select required className="mt-1 h-10 w-full rounded-md border bg-white px-3" value={form.candidateId} onChange={(event)=>setForm({...form,candidateId:event.target.value})}><option value="">اختيار المشارك</option>{dashboard.data?.ranking.map((candidate)=><option key={candidate.id} value={candidate.id}>{candidate.firstName} {candidate.lastName} — {candidate.totalPoints} نقطة</option>)}</select></div><div><Label>عدد النقاط (-50 إلى +50)</Label><Input className="mt-1" type="number" min={-50} max={50} required value={form.points} onChange={(event)=>setForm({...form,points:event.target.value})}/></div><div><Label>السبب الإجباري</Label><textarea required minLength={5} maxLength={500} className="mt-1 min-h-28 w-full rounded-md border p-3" value={form.reason} onChange={(event)=>setForm({...form,reason:event.target.value})} placeholder="شرح واضح لسبب التصحيح…"/></div><Button className="w-full bg-[#4A9B8E]" disabled={adjustment.isPending}>{Number(form.points)<0?<MinusCircle className="ml-2 h-4 w-4"/>:<PlusCircle className="ml-2 h-4 w-4"/>}تسجيل التصحيح</Button></div></form>
      <section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="flex items-center gap-2 text-xl font-black"><Trophy className="h-5 w-5 text-amber-600"/>الترتيب العام</h2><p className="mt-1 text-sm text-slate-500">{dashboard.data?.ranking.length??0} مشارك</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={exportRanking}><Download className="ml-1 h-4 w-4"/>CSV</Button><Button size="sm" variant="outline" onClick={()=>dashboard.refetch()}><RefreshCw className="h-4 w-4"/></Button></div></div><div className="max-h-[520px] divide-y overflow-auto">{dashboard.data?.ranking.map((candidate)=><div key={candidate.id} className="flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100 font-black">{candidate.rank}</span><div className="min-w-0 flex-1"><p className="truncate font-black">{candidate.firstName} {candidate.lastName}</p><p className="truncate text-xs text-slate-500" dir="ltr">{candidate.email}</p></div><b className="text-xl text-[#173f39]">{candidate.totalPoints}</b></div>)}</div></section></section>
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-black"><History className="h-5 w-5"/>السجل العام للنقاط</h2><p className="mt-1 text-sm text-slate-500">يشمل النقاط الآلية وجميع التصحيحات الإدارية.</p></div><div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400"/><Input className="w-full pr-9 sm:w-72" placeholder="الاسم، البريد أو السبب…" value={search} onChange={(event)=>setSearch(event.target.value)}/></div><select className="rounded-md border bg-white px-3" value={action} onChange={(event)=>setAction(event.target.value)}><option value="all">كل العمليات</option><option value="attendance">الحضور</option><option value="punctuality">الالتزام بالوقت</option><option value="manual_adjustment">التصحيحات الإدارية</option></select></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-right text-sm"><thead><tr className="border-b bg-slate-50"><th className="p-3">المشارك</th><th className="p-3">العملية</th><th className="p-3">النقاط</th><th className="p-3">السبب</th><th className="p-3">المسؤول</th><th className="p-3">التاريخ</th></tr></thead><tbody>{filteredHistory.map((entry)=><tr key={entry.id} className="border-b last:border-0"><td className="p-3 font-bold">{entry.firstName} {entry.lastName}</td><td className="p-3">{entry.title}</td><td className={`p-3 font-black ${entry.points<0?"text-red-600":"text-emerald-700"}`}>{entry.points>0?"+":""}{entry.points}</td><td className="max-w-sm p-3 text-slate-600">{entry.detail}</td><td className="p-3">{entry.adminName??"تلقائي"}</td><td className="whitespace-nowrap p-3" dir="ltr">{formatMoroccoDateTime(entry.awardedAt)}</td></tr>)}</tbody></table></div></section>
  </main></div>;
}
function csvCell(value:unknown){return `"${String(value??"").replaceAll('"','""')}"`;} function downloadCsv(csv:string,name:string){const url=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}
