import { useState } from "react";
import { CheckCircle2, LockKeyhole, LogIn, QrCode } from "lucide-react";
import { useParams } from "react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/providers/trpc";

export default function AttendanceCheckIn() {
  const { token = "" } = useParams(); const [form,setForm]=useState({email:"",password:""}); const [done,setDone]=useState<"new"|"existing"|null>(null);
  const session=trpc.attendance.sessionInfo.useQuery({token},{enabled:token.length===48,retry:false});
  const checkIn=trpc.attendance.checkIn.useMutation({onSuccess:(data)=>setDone(data.alreadyCheckedIn?"existing":"new")});
  return <div className="flex min-h-screen items-center justify-center bg-[linear-gradient(145deg,#edf8f5,#ffffff)] p-4" lang="ar" dir="rtl"><main className="w-full max-w-md rounded-3xl border bg-white p-7 shadow-xl">{session.isLoading?<div className="py-16 text-center">جارٍ التحقق من الرمز…</div>:session.isError?<div className="text-center"><LockKeyhole className="mx-auto h-14 w-14 text-red-500"/><h1 className="mt-4 text-2xl font-black">رمز غير صالح</h1><p className="mt-2 text-slate-500">{session.error.message}</p></div>:done?<div className="text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-600"/><h1 className="mt-4 text-2xl font-black">{done==="existing"?"تم تسجيل حضوركم مسبقاً":"تم تسجيل حضوركم بنجاح"}</h1><p className="mt-3 text-slate-500">{session.data?.title}</p></div>:<><div className="text-center"><QrCode className="mx-auto h-12 w-12 text-[#4A9B8E]"/><h1 className="mt-4 text-2xl font-black">تسجيل الحضور</h1><p className="mt-2 font-bold text-[#1f5148]">{session.data?.title}</p><p className="mt-1 text-sm text-slate-500">{session.data?.timeLabel}</p></div>{!session.data?.isOpen?<p className="mt-6 rounded-xl bg-amber-50 p-4 text-center font-bold text-amber-800">تم إغلاق تسجيل الحضور لهذه الحصة.</p>:<form className="mt-7 space-y-4" onSubmit={(e)=>{e.preventDefault();checkIn.mutate({token,email:form.email.trim().toLowerCase(),password:form.password});}}><div><Label htmlFor="email">البريد الإلكتروني</Label><Input id="email" type="email" required className="mt-1" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></div><div><Label htmlFor="password">كلمة المرور</Label><Input id="password" type="password" required className="mt-1" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/></div>{checkIn.error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{checkIn.error.message}</p>:null}<Button className="h-11 w-full bg-[#4A9B8E] hover:bg-[#3D7A6F]" disabled={checkIn.isPending}><LogIn className="ml-2 h-4 w-4"/>{checkIn.isPending?"جارٍ التسجيل…":"تأكيد حضوري"}</Button></form>}</>}</main></div>;
}
