import { ArrowRight, Award, CalendarCheck2, CheckCircle2, Clock3, Crown, Download, FileText, ListChecks, Medal, ShieldCheck, Sparkles, Trophy, Users } from "lucide-react";
import { Link } from "react-router";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { formatMoroccoDateTime } from "@/lib/morocco-time";
import { trpc } from "@/providers/trpc";

export default function FinalCandidateScores() {
  const scores = trpc.attendance.candidateScoreDashboard.useQuery(undefined, { retry: false, refetchInterval: 30000 });
  if (scores.isLoading) return <div className="candidate-orange-theme flex min-h-screen items-center justify-center bg-[#F4F8F7]"><div className="h-12 w-12 animate-spin rounded-full border-4 border-[#4A9B8E] border-t-transparent"/></div>;
  if (scores.isError) return <div className="min-h-screen bg-[#F4F8F7]" lang="ar" dir="rtl"><Navbar/><main className="mx-auto max-w-xl px-4 pt-32 text-center"><div className="rounded-3xl border bg-white p-8 shadow-sm"><Award className="mx-auto h-14 w-14 text-amber-500"/><h1 className="mt-4 text-2xl font-black">فضاء النقاط خاص بالمشاركين المؤكدين</h1><p className="mt-3 text-slate-600">{scores.error.message}</p><Link to="/signin?redirect=/espace-candidat-final/points"><Button className="mt-6 bg-[#4A9B8E]">تسجيل الدخول</Button></Link></div></main></div>;
  const data = scores.data;
  const attendancePoints = data.details.filter((entry) => entry.actionType === "attendance").reduce((sum, entry) => sum + entry.points, 0);
  const punctualityPoints = data.details.filter((entry) => entry.actionType === "punctuality").reduce((sum, entry) => sum + entry.points, 0);
  const dailyTaskPoints = data.details.filter((entry) => entry.actionType === "daily_task").reduce((sum, entry) => sum + entry.points, 0);
  const dailyFormPoints = data.details.filter((entry) => entry.actionType === "daily_form").reduce((sum, entry) => sum + entry.points, 0);
  const topFiveGroups = data.ranking.reduce<Array<typeof data.ranking>>((groups, candidate) => {
    const lastGroup = groups.at(-1);
    if (lastGroup?.[0]?.rank === candidate.rank) lastGroup.push(candidate);
    else groups.push([candidate]);
    return groups;
  }, []).filter((group) => (group[0]?.rank ?? Number.POSITIVE_INFINITY) <= 5);
  const currentCandidate = data.ranking.find((candidate) => candidate.isCurrentCandidate);
  const currentCandidateIsVisible = topFiveGroups.some((group) => group.some((candidate) => candidate.id === currentCandidate?.id));
  const exportRanking = () => { const csv=["Rang,Nom,Prénom,Points",...data.ranking.map((candidate)=>[candidate.rank,candidate.lastName,candidate.firstName,candidate.totalPoints].map((value)=>`"${String(value).replaceAll('"','""')}"`).join(","))].join("\r\n"); const url=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"})); const link=document.createElement("a");link.href=url;link.download="classement-points-edition-18.csv";link.click();URL.revokeObjectURL(url); };
  return <div className="candidate-orange-theme min-h-screen bg-[#F4F8F7] pb-16" lang="ar" dir="rtl"><Navbar/><main className="mx-auto max-w-7xl px-4 pt-24 sm:px-6">
    <header className="relative overflow-hidden rounded-2xl bg-[linear-gradient(125deg,#102f2b,#24695f_55%,#4A9B8E)] p-5 text-white shadow-xl sm:rounded-[2rem] sm:p-10"><div className="absolute -left-10 -top-10 h-52 w-52 rounded-full bg-amber-300/20 blur-3xl"/><div className="relative"><Link to="/espace-candidat-final" className="inline-flex items-center gap-2 rounded-xl bg-white/15 px-4 py-2 text-sm font-bold hover:bg-white/20"><ArrowRight className="h-4 w-4"/>العودة إلى فضاء المشاركين</Link><div className="mt-7 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-amber-300/15 px-4 py-2 text-sm font-bold text-amber-100"><Sparkles className="h-4 w-4"/>نقاط دورة الأثر</span><h1 className="mt-4 text-3xl font-black sm:text-5xl">لوحة تميزكم</h1><p className="mt-3 max-w-2xl leading-8 text-white/75">تابعوا نقاط الحضور والالتزام، واكتشفوا ترتيبكم بين جميع المشاركين.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 px-5 py-5 text-center backdrop-blur sm:rounded-3xl sm:px-8 sm:py-6"><p className="text-sm font-bold text-white/65">مجموع نقاطكم</p><p className="mt-1 text-6xl font-black text-amber-300">{data.candidate.totalPoints}</p><p className="mt-2 font-bold">المرتبة {data.candidate.rank} من {data.participantCount}</p></div></div></div></header>
    <section className="mt-6 grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-5"><ScoreCard icon={Trophy} label="مجموع النقاط" value={data.candidate.totalPoints} color="amber"/><ScoreCard icon={CalendarCheck2} label="نقاط الحضور" value={attendancePoints} color="emerald"/><ScoreCard icon={Clock3} label="مكافآت الالتزام بالوقت" value={punctualityPoints} color="sky"/><ScoreCard icon={ListChecks} label="نقاط المهام اليومية" value={dailyTaskPoints} color="emerald"/><ScoreCard icon={FileText} label="نقاط الاستمارات" value={dailyFormPoints} color="violet"/></section>
    <section className="mt-6 grid gap-4 lg:grid-cols-[1fr_1fr]"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-black"><ShieldCheck className="h-5 w-5 text-emerald-600"/>قواعد احتساب النقاط</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-amber-50 p-4"><b className="text-2xl text-amber-700">+{data.rules.earlyArrivalPoints}</b><p className="mt-1 text-sm">من {data.rules.earlyWindowMinutes} دقيقة قبل البداية حتى قبل موعدها</p></div><div className="rounded-xl bg-emerald-50 p-4"><b className="text-2xl text-emerald-700">+{data.rules.onTimePoints}</b><p className="mt-1 text-sm">من ساعة البداية إلى {data.rules.gracePeriodMinutes} دقائق بعدها</p></div><div className="rounded-xl bg-slate-100 p-4"><b className="text-2xl text-slate-700">{data.rules.latePoints}</b><p className="mt-1 text-sm">بعد مرور {data.rules.gracePeriodMinutes} دقائق</p></div></div><p className="mt-3 rounded-xl bg-sky-50 p-3 text-sm text-sky-800">قبل {data.rules.earlyWindowMinutes} دقيقة من البداية، رابط الحضور لا يعمل.</p><div className="mt-4"><div className="flex justify-between text-sm font-bold"><span>تقدم الحضور</span><span>{data.progress.attendedSessions} / {data.progress.totalSessions}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#4A9B8E]" style={{width:`${data.progress.totalSessions ? Math.min(100,(data.progress.attendedSessions/data.progress.totalSessions)*100) : 0}%`}}/></div></div></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-black"><Award className="h-5 w-5 text-amber-600"/>شاراتكم</h2>{data.badges.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{data.badges.map((badge)=><div key={badge.key} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-black text-amber-900">{badge.label}</p><p className="mt-1 text-sm text-amber-700">{badge.description}</p></div>)}</div>:<p className="mt-5 rounded-xl bg-slate-50 p-5 text-center text-slate-500">واصلوا الحضور للحصول على أول شارة.</p>}</div></section>
    <section className="mt-6 rounded-2xl border border-violet-200 bg-violet-50 p-4 shadow-sm sm:p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-violet-100 p-2.5 text-violet-700"><FileText className="h-5 w-5"/></div><div><h2 className="font-black text-violet-950">نقاط الاستمارات اليومية</h2><p className="mt-1 text-sm leading-6 text-violet-800">تحصلون على 5 نقاط عند إرسال الاستمارة خلال أول 24 ساعة من نشرها، و3 نقاط عند إرسالها بعد مرور 24 ساعة. لا تُحتسب الاستمارة أكثر من مرة.</p></div></div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between gap-3 border-b p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-amber-100 p-2 text-amber-700"><Crown className="h-5 w-5"/></div><div><h2 className="text-xl font-black">الترتيب العام</h2><p className="text-sm text-slate-500">أفضل 5 مراتب وترتيبكم الشخصي</p></div></div><Button size="sm" variant="outline" onClick={exportRanking}><Download className="ml-1 h-4 w-4"/>CSV</Button></div><div className="divide-y">{topFiveGroups.map((group) => group.length === 1 ? <CandidateRankingRow key={group[0].id} candidate={group[0]}/> : <RankingTieGroup key={group[0].rank} candidates={group}/>)}{currentCandidate && !currentCandidateIsVisible ? <div className="mt-3 border-t-4 border-dashed border-emerald-200"><CandidateRankingRow candidate={currentCandidate}/></div> : null}</div></section>
      <details className="group overflow-hidden rounded-3xl border bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center gap-3 p-5 transition hover:bg-slate-50"><div className="rounded-xl bg-emerald-100 p-2 text-emerald-700"><ListChecks className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h2 className="text-xl font-black">تفاصيل نقاطكم</h2><p className="text-sm text-slate-500">{data.details.length} عمليات مسجلة · اضغطوا لعرض التفاصيل</p></div><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xl text-slate-500 transition group-open:rotate-180">⌄</span></summary><div className="max-h-[680px] divide-y overflow-auto border-t">{data.details.length ? data.details.map((entry) => <div key={entry.id} className="p-4"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`mt-1 rounded-full p-2 ${entry.actionType === "punctuality" ? "bg-sky-100 text-sky-700" : entry.actionType === "daily_form" ? "bg-violet-100 text-violet-700" : "bg-emerald-100 text-emerald-700"}`}>{entry.actionType === "punctuality" ? <Clock3 className="h-4 w-4"/> : entry.actionType === "daily_form" ? <FileText className="h-4 w-4"/> : <CheckCircle2 className="h-4 w-4"/>}</div><div><p className="font-black leading-6">{entry.title}</p><p className="mt-1 text-sm text-slate-500">{entry.detail}</p><p className="mt-2 text-xs text-slate-400" dir="ltr">{formatMoroccoDateTime(entry.awardedAt)}</p></div></div><span className={`shrink-0 rounded-full px-3 py-1 font-black ${entry.points < 0 ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800"}`}>{entry.points > 0 ? "+" : ""}{entry.points}</span></div></div>) : <div className="p-10 text-center"><Users className="mx-auto h-12 w-12 text-slate-300"/><p className="mt-3 font-bold text-slate-500">ستظهر نقاطكم هنا بعد أول نشاط مسجل.</p></div>}</div></details></div>
  </main></div>;
}

function ScoreCard({ icon: Icon, label, value, color }: { icon: typeof Trophy; label: string; value: number; color: "amber" | "emerald" | "sky" | "violet" }) { const styles = { amber: "bg-amber-100 text-amber-700", emerald: "bg-emerald-100 text-emerald-700", sky: "bg-sky-100 text-sky-700", violet: "bg-violet-100 text-violet-700" }; return <div className="rounded-2xl border bg-white p-4 shadow-sm sm:p-5"><div className={`inline-flex rounded-xl p-2.5 sm:p-3 ${styles[color]}`}><Icon className="h-5 w-5"/></div><p className="mt-3 text-xs font-bold leading-5 text-slate-500 sm:mt-4 sm:text-sm">{label}</p><p className="mt-1 text-2xl font-black sm:text-3xl">{value} <span className="text-xs text-slate-400 sm:text-sm">نقطة</span></p></div>; }
function RankBadge({ rank }: { rank: number }) { if (rank <= 3) return <div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full font-black ${rank === 1 ? "bg-amber-100 text-amber-700" : rank === 2 ? "bg-slate-200 text-slate-700" : "bg-orange-100 text-orange-700"}`}><Medal className="h-5 w-5"/></div>; return <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 font-black text-slate-600">{rank}</div>; }
type RankingCandidate = { id: number; firstName: string; lastName: string; totalPoints: number; rank: number; isCurrentCandidate: boolean };
function CandidateRankingRow({ candidate }: { candidate: RankingCandidate }) { return <div className={`flex items-center gap-4 p-4 ${candidate.isCurrentCandidate ? "bg-emerald-50" : ""}`}><RankBadge rank={candidate.rank}/><div className="min-w-0 flex-1"><p className="truncate font-black">{candidate.firstName} {candidate.lastName}</p>{candidate.isCurrentCandidate ? <span className="text-xs font-bold text-emerald-700">هذا أنتم</span> : null}</div><div className="text-left"><b className="text-xl text-[#173f39]">{candidate.totalPoints}</b><span className="mr-1 text-xs text-slate-500">نقطة</span></div></div>; }
function RankingTieGroup({ candidates }: { candidates: RankingCandidate[] }) { const first = candidates[0]; return <details className="group"><summary className={`flex cursor-pointer list-none items-center gap-4 p-4 transition hover:bg-amber-50 ${candidates.some((candidate) => candidate.isCurrentCandidate) ? "bg-emerald-50" : ""}`}><RankBadge rank={first.rank}/><div className="min-w-0 flex-1"><p className="font-black">{candidates.length} مشاركين في نفس المرتبة</p><p className="mt-1 text-xs text-slate-500">اضغطوا لعرض الأسماء</p></div><div className="text-left"><b className="text-xl text-[#173f39]">{first.totalPoints}</b><span className="mr-1 text-xs text-slate-500">نقطة</span></div><span className="text-slate-400 transition group-open:rotate-180">⌄</span></summary><div className="divide-y border-t bg-slate-50/60">{candidates.map((candidate) => <div key={candidate.id} className={`flex items-center gap-3 px-6 py-3 ${candidate.isCurrentCandidate ? "bg-emerald-100/70" : ""}`}><span className="h-2 w-2 rounded-full bg-amber-400"/><p className="min-w-0 flex-1 truncate font-bold">{candidate.firstName} {candidate.lastName}</p>{candidate.isCurrentCandidate ? <span className="text-xs font-black text-emerald-700">هذا أنتم</span> : null}</div>)}</div></details>; }
